version: '2'

services:
    web:
        image: nginx:1.16
        ports:
            - "8080:80"
        volumes:
            - .:/fieldtrip
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - code-network
        depends_on:
            - php
    php:
        image: php:7.3-fpm
        user: 1000:1000
        volumes:
            - .:/fieldtrip
        networks:
            - code-network

networks:
    code-network:
        driver: bridge
